language: ruby
bundler_args: --without tools
script: "bundle exec rake spec"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-9.0.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
