language: ruby
bundler_args: --without tools
after_success:
- '[ "$TRAVIS_RUBY_VERSION" = "2.5.0" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
script: "bundle exec rake spec"
rvm:
  - 2.3.4
  - 2.4.1
  - 2.5.0
  - jruby-9.1.12.0
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-9.1.12.0
    - rvm: rbx-2
    - rvm: ruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
